import { Character } from '@app/interfaces/Character';
import { Stats } from '@app/interfaces/Stats';

export const DEFAULT_STATS: Stats = { health: 4, speed: 4, attack: 4, defense: 4 };
export const CHARACTERS: Character[] = [
    {
        name: 'A.S.H.',
        image: 'assets/avatars/A.S.H..png',
        face: 'assets/avatars-face/A.S.H.-face.png',
        body: 'assets/avatars-top/A.S.H..png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Boulder',
        image: 'assets/avatars/Boulder.png',
        face: 'assets/avatars-face/Boulder-face.png',
        body: 'assets/avatars-top/Boulder.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Kyron',
        image: 'assets/avatars/Kyron.png',
        face: 'assets/avatars-face/Kyron-face.png',
        body: 'assets/avatars-top/Kyron.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Morrow',
        image: 'assets/avatars/Morrow.png',
        face: 'assets/avatars-face/Morrow-face.png',
        body: 'assets/avatars-top/Morrow.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Neticus',
        image: 'assets/avatars/Neticus.png',
        face: 'assets/avatars-face/Neticus-face.png',
        body: 'assets/avatars-top/Neticus.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Nova',
        image: 'assets/avatars/Nova.png',
        face: 'assets/avatars-face/Nova-face.png',
        body: 'assets/avatars-top/Nova.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Raximus',
        image: 'assets/avatars/Raximus.png',
        face: 'assets/avatars-face/Raximus-face.png',
        body: 'assets/avatars-top/Raximus.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Seraphine',
        image: 'assets/avatars/Seraphine.png',
        face: 'assets/avatars-face/Seraphine-face.png',
        body: 'assets/avatars-top/Seraphine.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Symia',
        image: 'assets/avatars/Symia.png',
        face: 'assets/avatars-face/Symia-face.png',
        body: 'assets/avatars-top/Symia.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Vrox',
        image: 'assets/avatars/Vrox.png',
        face: 'assets/avatars-face/Vrox-face.png',
        body: 'assets/avatars-top/Vrox.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Xal',
        image: 'assets/avatars/Xal.png',
        face: 'assets/avatars-face/Xal-face.png',
        body: 'assets/avatars-top/Xal.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
    {
        name: 'Zaner',
        image: 'assets/avatars/Zaner.png',
        face: 'assets/avatars-face/Zaner-face.png',
        body: 'assets/avatars-top/Zaner.png',
        stats: { ...DEFAULT_STATS },
        dice: '',
        victories: 0,
        position: { row: 0, col: 0 },
        initialPosition: { row: 0, col: 0 },
    },
];
